export const GET_CONTACTS = "GET_CONTACTS"
export const GET_CONTACTS_SUCCESS= "GET_CONTACTS_SUCCESS"
export const GET_CONTACTS_FAIL="GET_CONTACTS_FAIL"

export const ADD_CONTACT = "ADD_CONTACT"
export const ADD_CONTACT_SUCCESS="ADD_CONTACT_SUCCESS"
export const ADD_CONTACT_FAIL="ADD_CONTACT_FAIL"

export const DELETE_CONTACT = "DELETE_CONTACT"

//Error Contants
export const GET_ERRORS = "GET_ERRORS" 
export const CLEAR_ERRORS = "CLEAR_ERRORS"

// Auth Constants

export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";